### ISSUE TITLE
Changing of background color of the bars?

### ISSUE THREAD

**Issue by kneza23** [zoontek/react-native-bars#1]
### Why it is needed?

Possibility to programatically change background color of status bar and navigation bar.

### Possible implementation

API could look like default <StatusBar backgroundColor="black"/> component from core RN repo.

**Comment by zoontek** [comment]
That's not the purpose of this library. Its purpose is fully transparent status / navigation bars, similar as iOS behaviour.

But as both status and navigation bar height are exposed, you can create  `<View />` with custom `backgroundColor` if needed.
