### ISSUE TITLE
Style setting for navigation bar

### ISSUE THREAD

**Issue by leruse4ka** [zoontek/react-native-bars#52]
### Why it is needed?

For the status bar there is an option to set other styles separately, but for the navigation bar there is no such option. Sometimes it is required. I would be very grateful if you could consider adding a separate method.

### Code sample

```js
SystemBars.pushStackEntry({navBarStyle: isDarkMode ? 'light' : 'dark'})
```

**Comment by zoontek** [comment]
@leruse4ka This is not required, as the navigation bar style is automatic when gesture navigation is enabled, and semi-opaque when buttons navigation is enabled, similar to Android 15 default behavior:

![Screenshot 2024-11-29 at 11 42 49](https://github.com/user-attachments/assets/b225a561-4b2f-4ed3-83d8-ba8bc16912a0)

**Comment by leruse4ka** [comment]
When status-bar need light, but navigation-bar need dark this create a problem.

**Comment by zoontek** [comment]
@leruse4ka When buttons navigation bar is used:

If the phone is in light mode -> the navigation bar has a light semi-opaque background, the button style is dark

If the phone is in dark mode -> the navigation bar has a dark semi-opaque background, the button style is light

So there's no need to set the navigation bar style, it always has enough contrast. Except if you override the default style using another library, but this is out of the scope of react-native-edge-to-edge, which only aligns with the Android 15 default behavior.

**Comment by exzos28** [comment]
Everyone who has a theme controlled from the app and has the `navigationBar` color unsynchronized with the theme, then send in `Appearance.setColorScheme` scheme when changing the theme.
This turned out to be a discovery for me.

**Comment by tnortman-jabra** [comment]
@zoontek 

> @leruse4ka When buttons navigation bar is used:

> If the phone is in light mode -> the navigation bar has a light semi-opaque background, the button style is dark
> 
> If the phone is in dark mode -> the navigation bar has a dark semi-opaque background, the button style is light
> 
> So there's no need to set the navigation bar style, it always has enough contrast.
> Except of course if you override the default style using another library, but this is out of the scope of react-native-edge-to-edge, which only aligns with the Android 15 default behavior.

```
if (VERSION.SDK_INT >= VERSION_CODES.O_MR1 && isNavigationBarTransparent(activity)) {
      window.navigationBarColor = Color.TRANSPARENT

      if (VERSION.SDK_INT >= VERSION_CODES.Q) {
        window.isStatusBarContrastEnforced = false
        window.isNavigationBarContrastEnforced = false
      }
    } else {
      val light = isDefaultLightSystemBars(activity)

      window.navigationBarColor = when {
        VERSION.SDK_INT >= VERSION_CODES.Q -> Color.TRANSPARENT
        VERSION.SDK_INT >= VERSION_CODES.O_MR1 && light -> LightNavigationBarColor
        else -> DarkNavigationBarColor
      }

      insetsController.run {
        isAppearanceLightNavigationBars = when {
          VERSION.SDK_INT >= VERSION_CODES.O_MR1 -> light
          else -> false
        }
      }
```
Can you clarify the expected behavior? If:
- app `minSdkVersion` is 29, AND
- enforceNavigationBarContrast is true (default)

then the `navigationBarColor` will always be transparent. There is no way to control the navigation bar color when a user is using the three button navigation?

More plainly, if an app has a `minSdkVersion` of <= 29, then the navigationBarColor will always be transparent.

Do you think it's possible to support controlling the navigation bar color? For example, an app may have a mix of dark and light screens so, the `window.navigationBarColor = Color.TRANSPARENT` will not always work.

I am confused about how this package should work of the box given the above and this statement:

> when gesture navigation is enabled, and semi-opaque when buttons navigation is enabled

**Comment by zoontek** [comment]
`minSdkVersion` has nothing to do with the phone running version.

> Do you think it's possible to support controlling the navigation bar color?

No, this is a deprecated API.

> Do you think it's possible to support controlling the navigation bar color? For example, an app may have a mix of dark and light screens so, the window.navigationBarColor = Color.TRANSPARENT will not always work.

In this case either you keep the Android default colors (very dark gray color or white), or you set an absolutely positionned View if the bottom inset is kinda big (aka, not the gesture bar)

Android also added [this](https://developer.android.com/reference/kotlin/androidx/core/view/insets/Protection) in Android 16 beta, we will see.

**Comment by tnortman-jabra** [comment]
@zoontek Thanks for the quick reply

```
window.navigationBarColor = when {
        VERSION.SDK_INT >= VERSION_CODES.Q -> Color.TRANSPARENT // remove this line
        VERSION.SDK_INT >= VERSION_CODES.O_MR1 && light -> LightNavigationBarColor
        else -> DarkNavigationBarColor
      }
```

> Do you think it's possible to support controlling the navigation bar color?

Poor wording on my part - I would like to choose between a LightNavigationBarColor and a DarkNavigationBarColor.

I think if we remove the `VERSION.SDK_INT >= VERSION_CODES.Q -> Color.TRANSPARENT` line above when dealing with users who specify `enforceNavigationBarContrast: true`, it would make sense.

I am having a hard time imagining what case the nav bar should be transparent if the consumer specifies `enforceNavigationBarContrast: true`. Can you shed light on why this is the behavior for those with a `minSdkVersion` <= 29?

**Comment by zoontek** [comment]
The behavior is aligned with how edge-to-edge is enforced on Android 15, nothing more.

**Comment by tnortman-jabra** [comment]
> Here, setting Color.TRANSPARENT has only an effect with gesture navigation

I think this is not true if I read this correctly from the [Edge to Edge enforcement docs](https://developer.android.com/about/versions/15/behavior-changes-15#edge-to-edge)

> [setNavigationBarColor](https://developer.android.com/reference/android/view/Window#setNavigationBarColor(int)) and R.attr#navigationBarColor are set to match the window background by default. The window background must be a color drawable for this default to apply. This API is deprecated but continues to affect 3-button navigation.

And from the [Android Edge to Edge code](https://github.com/androidx/androidx/blob/ce9bc71b22d9ddf37416d022a177365d3c721a63/activity/activity/src/main/java/androidx/activity/EdgeToEdge.kt#L122C12-L124C93) itself: 
```
         * - On API level 29 and above, both the status bar and the navigation bar will be
         *   transparent. However, the navigation bar with 3 or 2 buttons will have a translucent
         *   scrim. This scrim color is provided by the platform and *cannot be customized*.
```
So I think if the intent for this package is to emulate this behavior, it should be enforcing the scrim color when a user decides to `enforceNavigationBarContrast: true`.

Thanks for your engagement with me on this, I'm trying to wrap my head around it and the codebase!

**Comment by zoontek** [comment]
That's what the package is doing when enforceNavigationBarContrast is set to true: transparent gesture navigation bar, scrim for buttons navigation bar.

Try different configurations on  Android 15 (SDK 35) - with edge-to-edge enforced, react-native-edge-to-edge not installed, to compare 🙂
