### ISSUE TITLE
bar color changed by setSoftInputMode

### ISSUE THREAD

**Issue by web3luhao** [zoontek/react-native-bars#6]
### Bug summary

bar color changed by setSoftInputMode, maybe other native operations.

I tried to use this package in a project which uses [wix/react-native-ui-lib](https://github.com/wix/react-native-ui-lib) v5, the bar colors are changed when keyboard shown etc.

https://user-images.githubusercontent.com/95836286/148735227-37861f90-bd00-4af1-9927-5ae9efc8020b.mp4

in my reproduction setSoftInputMode is called after 4s.

### Library version

1.1.1

### Environment info

```shell
System:
    OS: macOS 11.6.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 68.87 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.n/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - ~/.n/bin/npm
    Watchman: 2022.01.03.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 24, 28, 29, 30, 31, 32
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 32.0.0
      System Images: android-30 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /Users/user1/.jenv/shims/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.4 => 0.66.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. call window.setSoftInputMode after bars config.

### Reproducible sample code

[sample code](https://github.com/web3luhao/react-native-bars/tree/reproduce)

**Comment by zoontek** [comment]
It appears to be an issue with AndroidX core package: https://developer.android.com/jetpack/androidx/releases/core
I will report an issue in their bug tracker

**Comment by web3luhao** [comment]
> It appears to be an issue with AndroidX core package: https://developer.android.com/jetpack/androidx/releases/core I will report an issue in their bug tracker.

Can you give me a link for that issue?

**Comment by zoontek** [comment]
Before reporting it, I tried to reproduce it on my devices (Xiaomi A2 on Android 10, Pixel 4a on Android 12) and I couldn't.
What device do you have? (model + android version + possible custom UI)

**Comment by web3luhao** [comment]
> Before reporting it, I tried to reproduce it on my devices (Xiaomi A2 on Android 10, Pixel 4a on Android 12) and I couldn't. What device do you have? (model + android version + possible custom UI)

The video was took on my redmi k40 ArrowOS android 11, the issue do appear in emulator Pixel 4a android 11

**Comment by zoontek** [comment]
@web3luhao Could you try if the new release ([1.2.0](https://github.com/zoontek/react-native-bars/releases/tag/1.2.0)) fixes the issue? As it updates to AndroidX core `1.8.0`, it might be.
